baseURL = 'https://test.kelvinism.com/'
languageCode = 'en-us'
title = "Kelvin Nicholson"

[permalinks]
posts = "/:year/:month/:title"


[params]
disableSpecial1stPost = true
ShowReadingTime = true
ShowBreadCrumbs = false
defaultTheme = "light"
ShowPostNavLinks = false

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true